<?php

declare(strict_types=1);

namespace Axleus\Tooling\Template;

final class TemplateSkeletons
{
    public const HTMX_SKELETON = <<<'EOS'
    <?php
    declare(strict_types=1);
    ?>
    <article>
        <div>
            <h2 class="pico-color-jade-500">Axleus Tooling Template</h2>
            <p>
                This template file was autogenerated by Axleus Tooling. Please modify as needed!!!
            </p>
        </div>
    </article>
    EOS;

    public const GENERIC_SKELETON = <<<'EOS'
    <?php
    declare(strict_types=1);
    ?>
    Template for %s
    EOS;
}
